import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'

import Header from '../components/Header'
import MatchingBody from '../components/MatchingBody'

function Matching() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>전픽</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex justify-center m-0 p-0 bg-gray-200">
        <div className="sm:w-[420px] w-full m-0 p-0 bg-white min-h-screen">
          {/* Header */}
          <Header />

          {/* Body */}
          <MatchingBody />

          {/* Footer */}
        </div>
      </div>
    </>
  )
}

export default Matching
